let val = 'input here'
let val12, val13 = 'input here'
//12-16, 17-19, 20-25, 26-32
let labels = [
`Call Type : ${val}`,
`Call Reason : ${val}`,
`Speaking To : ${val}`,
`Patient First Name : ${val}`,
`Patient Last Name : ${val}`,
`Authorized Person Name : ${val}`,
`Advised Caller: : ${val}`,
`Patient added authorized user : ${val}`,
`Authorized Representative Name : ${val}`,
`What is your relationship with this person? : ${val}`,
`Other (relationship) : ${val}`,
`Preferred phone number is: ${val12}  ${val13}`,
`Is this phone number a mobile number or landline phone? : ${null}`,
`Is the phone number we have on file the best phone number to reach you : ${null}`,
`Added addtl number ${val} Mobile`,
`Added addtl number ${val} Landline`,
`Verify/Obtain Correct Email address (if not email address - don't confirm ask for email) : ${val}`,
`Confirmed email address: ${val}`,
`Email address : ${val}`,
`I want to confirm we are shipping your supplies to: : ${val}`,
`City : ${val}`,
`State : ${val}`,
`Zip : ${val}`,
`Is this address correct? : ${val}`,
`Please provide us with your updated shipping address. : ${val}`,
`Current Healthcare Provider First Name : ${val}`,
`Current Healthcare Provider Last Name : ${val}`,
`Current Healthcare Provider Address : ${val}`,
`New Healthcare Provider First Name : ${val}`,
`New Healthcare Provider Last Name : ${val}`,
`New Healthcare Provider Address : ${val}`,
`New Healthcare Provider Phone number : ${val}`,
`Primary Insurance Policy/ID Number : ${val}`,
`Insurance Company Name (as listed on your insurance card) : ${val}`,
`Policy/ID Number : ${val}`,
`Group Number : ${val}`,
`Relationship to Policyholder : ${val}`,
`Policyholder Name : ${val}`,
`Policyholder Date of Birth : ${val}`,
`Secondary Insurance Policy/ID Number : ${val}`,
`Secondary Insurance Company Name (as listed on your insurance card) : ${val}`,
`Secondary Policy/ID Number : ${val}`,
`Group Number : ${val}`,
`Relationship to Policyholder : ${val}`,
`Policyholder Name : ${val}`,
`Policyholder Date of Birth : ${val}`,
`Patient is: ${val}`,
`Patient is: ${val}`,
`and testing frequency is ${val}; `,
`injection frequency is  ${val}; `,
`Injecting  ${val} units of insulin each day;`,
`injecting 3+ times per day since  ${val}`,
`Current Pump Model:  ${val}`,
`Serial #:  ${val}`,
`Insurance that paid: ${val}`,
`Date of Purchase: ${val}`,
`Experienced Malfunctions: ${val}`,
`Other Malfunctions:  ${val}`,
`Patient is electing to get a replacement pump`,
`Patient is currently on a pump and has used it continuously since receiving it on this date: ${val}`,
`Site Change Frequency: ${val}`,
`Days on Hand:  ${val}`,
`Are you currently using a Medtronic Insulin Pump? : ${val}`,
`What brand of Medtronic Isulin Pump are you using? : ${val}`,
`Do you want your Medtronic CGM to work with your Medtronic Insulin Pump? : ${val}`,
`Do you want your Medtronic CGM to work with your cell phone? : ${val}`,
`Are you currently using a Dexcom CGM with your insulin pump or insulin pen? : ${val}`,
`Dexcom G7 CGM will not pair with your pump/pen.  Do you want to continue with Dexcom G6 CGM at this time, you can do software upgrade when G7 integration is available. : ${val}`,
`Current Brand/Model : ${val}`,
`Serial Number (Reader/Reciever) : ${val}`,
`Insurance that paid : ${val}`,
`Date of Purchase : ${val}`,
`Days on Hand : ${val}`,
`Are you administering insulin? : ${val}`,
`Do you have frequent, recurring hypoglycemic episodes? : ${val}`,
`CGM90 Day Program Requirements : ${val}`,
`Patient Opted in to CGM90 : ${val}`,
`Advised Patient their pump supplies will ship every: : ${val}`,
`Advised Patient their CGMS supplies will ship every: : ${val}`,
`Advised Benefits/Out-of-pocket (Advised Medicare 13-month rental payment method). : ${val}`,
`Is this an exchange plan? : ${val}`,
`Advised Benefits/OOP : ${val}`,
`Informed Patient: : ${val}`,
`Is patient covered at 100%? : ${val}`,
`Medtronic Trade-In Pump Credit : ${val}`,
`Based on insurance and products, the patients Expected patient responsibility is: : ${val}`,
`Preferred Insulin Pump Brand : ${val}`,
`Preferred Beta Bionics Model : ${val}`,
`Preferred Medtronic Model : ${val}`,
`Preferred Tandem Model : ${val}`,
`Quantity : ${val}`,
`Preferred Reservoir Brand : ${val}`,
`Preferred Beta Bionics Reservoir Model : ${val}`,
`Preferred Medtronic Reservoir Model : ${val}`,
`Preferred Tandem Reservoir Model : ${val}`,
`Quantity : ${val}`,
`Preferred Infusion Set Brand : ${val}`,
`Preferred Beta Bionics Infusion Set Model : ${val}`,
`Preferred Medtronic Infusion Set Model : ${val}`,
`Preferred Tandem Infusion Set Model : ${val}`,
`Quantity : ${val}`,
`Other Supplies: Brand : ${val}`,
`Other: 3M Model : ${val}`,
`Other: Energizer Model : ${val}`,
`Other: Ferndale Lab Model : ${val}`,
`Other: Medtronic Model : ${val}`,
`Other: Smith & Nephew Model : ${val}`,
`Other: Smith's Medical : ${val}`,
`Other: Torbot Group Inc. : ${val}`,
`Quantity : ${val}`,
`Preferred CGM Product : ${val}`,
`Preferred Dexcom Transmitter Model : ${val}`,
`Preferred Medtronic Transmitter Model : ${val}`,
`Quantity : ${val}`,
`Preferred Receiver (optional) Brand : ${val}`,
`Preferred Abbott Receiver Model : ${val}`,
`Preferred Dexcom Receiver Model : ${val}`,
`Preferred Medtronic Receiver Model : ${val}`,
`Preferred Tandem Receiver Model : ${val}`,
`Quantity : ${val}`,
`Preferred Sensor Brand : ${val}`,
`Preferred Abbott Sensor Model : ${val}`,
`Preferred Dexcom Sensor Model : ${val}`,
`Preferred Medtronic Sensor Model : ${val}`,
`Quantity : ${val}`,
`Medtronic Quickserter : ${val}`,
`Quantity : ${val}`,
`Advise Patient: : ${val}`,
`Reviewed 90 Day physician visits with patient: : ${val}`,
`Estimated Cost Statement - if 100% does this have to be read? : ${val}`,
`Advised Patient of Next Steps : ${val}`,
`Patient advised of re-order proces : ${val}`]

